import type { Account, Message } from "./types";

export const initialAccounts: Account[] = [
  {
    id: "acc-wa-01",
    platform: "whatsapp",
    name: "北美客服",
    handle: "+1 202 ••• ••81",
    status: "online",
    messagesToday: 46,
    lastSync: "刚刚",
    translationEnabled: true,
    accent: "#23c483",
  },
  {
    id: "acc-tg-01",
    platform: "telegram",
    name: "欧洲市场",
    handle: "@euro_support",
    status: "online",
    messagesToday: 23,
    lastSync: "1 分钟前",
    translationEnabled: true,
    accent: "#50a7ea",
  },
  {
    id: "acc-rcs-01",
    platform: "rcs",
    name: "订单通知",
    handle: "Pixel 8 Pro",
    status: "expired",
    messagesToday: 0,
    lastSync: "2 小时前",
    translationEnabled: false,
    accent: "#8b7cf6",
  },
];

export const initialMessages: Message[] = [
  {
    id: "msg-01",
    platform: "whatsapp",
    accountName: "北美客服",
    contact: "Olivia Martin",
    original: "Hi, can you confirm when my order will arrive?",
    translation: "你好，可以确认一下我的订单什么时候送达吗？",
    time: "10:42",
    direction: "inbound",
    unread: true,
  },
  {
    id: "msg-02",
    platform: "telegram",
    accountName: "欧洲市场",
    contact: "Luca Bianchi",
    original: "Do you ship to Milan?",
    translation: "你们可以配送到米兰吗？",
    time: "10:31",
    direction: "inbound",
    unread: true,
  },
  {
    id: "msg-03",
    platform: "whatsapp",
    accountName: "北美客服",
    contact: "Emma Wilson",
    original: "Your replacement has been dispatched.",
    translation: "您的换货商品已经发出。",
    time: "09:58",
    direction: "outbound",
  },
];
